### PR TITLE
update setup.py

### PR DESCRIPTION
**Pull request by dgketchum**
This should allow one to download the package from pip, and use the `fels` command, rather than typing out the file name.

This is based on my own (USGS-based) landsat downloader https://github.com/dgketchum/Landsat578/blob/master/setup.py that I have operational on pip.  USGS was down today and I started to work on building gcs functionality and found your project!

A great resource describing how to push new 'tags' (aka versions) to pip is here:  http://peterdowns.com/posts/first-time-with-pypi.html.

### CODE REVIEW

**Comment by dgketchum** [comment]
should have tagged this #30

**Comment by vascobnunes** [comment]
Thank you for your collaboration. We will test this and merge.

**Comment by vascobnunes** [comment]
@dgketchum I tried your setup.py but after uploading to pypi and trying to install I get the following error (see screenshot)
image

**Comment by dgketchum** [comment]
@vascobnunes, I looked this over and created a patch that follows the naming conventions of other packages (including one of my own) that should allow this to upload as a package

**Comment by vascobnunes** [comment]
yup, this works now. thanks a lot @dgketchum

**Pull request merged**
